export enum ClaimListFilterSelection {
    DR_NAME = "DR_NAME",
    MEMBERID = "MEMBERID",
    NATIONALID = "NATIONALID",
    PATIENTFILENO = "PATIENTFILENO",
    CLAIMDATE = "CLAIMDATE",
    CLAIMREFNO = "CLAIMREFNO"
}