export enum ClaimStatus{
    ALL = "All",
    Accepted = "Accepted",
    NotAccepted = "NotAccepted",
    Not_Saved = "Not Saved" ,
    // Duplicated = "Duplicate",
    // Batched = 'Batched',
    INVALID = 'INVALID',
    Failed = 'Failed',
    
    VALID = "VALID",
    ELIGIBLE = "ELIGIBLE",
    INELIGIBLE = "INELIGIBLE",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    PARTIALLY_APPROVED= "PARTIALL APPROVED",
    // LIMIT_APPROVED ="LIMI APPROVED",
    // CONDITIONALLY_APPROVED = "CONDITIONALL APPROVED",
    // PENDING = "PENDING",
    // CANCELLED = "CANCELLED",
    // REFERRED = "REFERRED",
    // FURTHER_DETAILS_REQUIRED = "FURTHER DETAIL REQUIRED",
    // UNDER_PROCESS = "UNDE PROCESS",
    SETTLED = "SETTLED",
    PAID = "PAID",
    PARTIALLY_PAID = "PARTIALL PAID",
    OUTSTANDING = "OUTSTANDING",
    // RETURNED = "RETURNED",
    // DUPLICATE = "DUPLICATE",
    // DISPENSED = "DISPENSED",
    // PARTIALLY_DISPENSED = "PARTIALL DISPENSED",
    // NOT_DISPENSED = "NO DISPENSED",
    // NO_APPROVAL_REQUIRED= "No Approva Required",
}