export enum ClaimListFilterSelection {
    DR_NAME = 'DR_NAME',
    MEMBERID = 'MEMBERID',
    NATIONALID = 'NATIONALID',
    PATIENTFILENO = 'PATIENTFILENO',
    CLAIMDATE = 'CLAIMDATE',
    CLAIMREFNO = 'CLAIMREFNO',
    CLAIMNET = 'CLAIMNET',
    ISREALTED = 'ISRELATEDCLAIM',
    BATCHNUM = 'BATCHNUM'
}
