apiVersion: v1
kind: Service
metadata:
  name: gui
  namespace: qa
  labels:
    app: gui
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: gui
