apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: prod
  labels:
    app: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      nodeSelector:
        environment: production
      containers:
        - name: gui
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/prod/gui:latest
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: ocir-login-credentials
