apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: dr
  labels:
    app: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
        - name: gui
          image: registry.waseel.com:5000/dr/gui:latest
          ports:
          - containerPort: 8080