# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: DEMO - Angular Build

on:
  workflow_dispatch:

      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and npm run build
      run: |
        npm install -s
        npm run buildOciQA

    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login me-jeddah-1.ocir.io -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Build
      run: docker build . -t me-jeddah-1.ocir.io/ax7dvcawpc84/demo/gui:latest -t me-jeddah-1.ocir.io/ax7dvcawpc84/demo/gui:${{ github.sha }}

    - name: Docker Push
      run: docker push --all-tags me-jeddah-1.ocir.io/ax7dvcawpc84/demo/gui

    - name: Deploy to K8S
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_ON_PREMISE }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: set image --record deployment/gui gui=me-jeddah-1.ocir.io/ax7dvcawpc84/demo/gui:${{ github.sha }} -n demo

    - name: Verify Deployment
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_ON_PREMISE }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: '"rollout status deployment/gui -n demo"'
