# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create QA K8s Objects

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create on K8S
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.ECLAIMS_KUBE_CONFIG_QA }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: apply -f .k8s/qa
