export enum SummaryType {
    invalMem = 1,
    diffInCom = 2,
    claNotRec = 3,
    invaSouCod = 4,
    lateSub = 5,
    subTotBatDiff = 6,
    approCare = 7,
    techContr = 8,
    followUpPeriod = 8.1,
    management = 8.2,
    finSettled = 8.3,
    priceShortFall = 9,
    waitingPeriod = 9.1,
    insPolicy = 9.2,
    serProvided = 9.3,
    poliCompi = 10,
    preAuth = 11,
    reqPolicy = 11.1,
    authRequest = 11.2,
    preAuthorization = 11.3,
    unwanTedVar = 12,
    pharmecyBen = 13,
    subTotDed = 14,
    presentNetBill = 15,
    batcDiff = 16,
    disDiff = 17,
    dedDiff = 18,
    deduct = 19,
    pending = 20,
    grTotRejAm = 21,
    approPay = 22

}
